# Production Docker Compose Configuration
# Usage: docker compose -f compose.prod.yaml up -d
# Required: .env file with DB credentials

services:
  db:
    container_name: time_manager_db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - time-manager-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: time_manager_backend
    image: ghcr.io/leopartt/time_manager/backend:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      BACKEND_PROFILE: prod
      APP_NAME: ${APP_NAME}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      SERVER_PORT: ${SERVER_PORT:-8080}
      ACTUATOR_PORT: ${ACTUATOR_PORT}
    networks:
      - time-manager-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${ACTUATOR_PORT:-8080}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  time-manager-network:
    driver: bridge

volumes:
  postgres_data: